-- Add excerpt field to processed_articles table
ALTER TABLE processed_articles
ADD COLUMN excerpt TEXT;

-- Update existing records with a default excerpt (first 300 chars of content)
UPDATE processed_articles
SET excerpt = SUBSTRING(content FROM 1 FOR 300) || '...'
WHERE excerpt IS NULL;

-- Add comment to explain the field
COMMENT ON COLUMN processed_articles.excerpt IS 'Dramatic excerpt/subtitle for the article, generated by LLM';